### ISSUE TITLE
Build database infrasturcture

### ISSUE THREAD

**Issue by mehai** [mehai/argolib#2]
**Create database infrastructure using either hibernate or mysql having following tables:**

- Users

- Books

- Reviews

- Reservations

All identified by id - primary key.

### Relationships:

- **Books** - _ONE to MANY_ - **Reservations, Reviews**

- **Users** - _ONE to MANY_ - **Reservations, Reviews**

**Comment by osopromadze** [comment]
check pull request https://github.com/mehai/argolib/pull/3
